---
title: Testing for funnel plot asymmetry of standardized mean differences
author:
- name:
    given: James E.
    family: Pustejovsky
- name:
    given: Melissa A.
    family: Rodgers
date: 2019-03-01T00:00:00
categories:
- meta-analysis
- publication bias
links:
- text: Journal
  url: https://doi.org/10.1002/jrsm.1332
  icon: newspaper
- icon: unlock-fill
  text: Pre-Print
  url: https://psyarxiv.com/ea6kz/
- icon: code-slash
  text: Code
  url: https://osf.io/4ntcy/
citation:
  type: article-journal
  container-title: Research Synthesis Methods
  url: https://doi.org/10.1002/jrsm.1332
  doi: 10.1016/j.jsp.2018.02.003
  volume: 10
  issue: 1
  page: 57-71

---


Publication bias and other forms of outcome reporting bias are critical threats to the validity of findings from research syntheses. A variety of methods have been proposed for detecting selective outcome reporting in a collection of effect size estimates, including several methods based on assessment of asymmetry of funnel plots, such as Egger's regression test, the rank correlation test, and the Trim-and-Fill test. Previous research has demonstated that Egger's regression test is mis-calibrated when applied to log-odds ratio effect size estimates, due to artifactual correlation between the effect size estimate and its standard error. This study examines similar problems that occur in meta-analyses of the standardized mean difference, a ubiquitous effect size measure in educational and psychological research. In a simulation study of standardized mean difference effect sizes, we assess the Type I error rates of conventional tests of funnel plot asymmetry, as well as the likelihood ratio test from a three-parameter selection model. Results demonstrate that the conventional tests have inflated Type I error due to correlation between the effect size estimate and its standard error, while tests based on either a simple modification to the conventional standard error formula or a variance-stabilizing transformation both maintain close-to-nominal Type I error.


