---
title: 'Determining associations between intervention amount and outcomes for young
  autistic children: A systematic review and meta-analysis'
author:
- name:
    given: Micheal
    family: Sandbank
- name:
    given: James E.
    family: Pustejovsky
- name:
    given: Kristen
    family: Bottema-Beutel
- name:
    given: Nicolette
    family: Caldwell
- name:
    given: Jacob I.
    family: Feldman
- name:
    given: Shannon Crowley
    family: LaPoint
- name:
    given: Tiffany
    family: Woynaroski
date: 2024-06-24T00:00:00
categories:
- systematic review
- autism
- meta-analysis
links:
- text: Journal
  url: https://doi.org/10.1001/jamapediatrics.2024.1832
  icon: newspaper
- icon: code-slash
  text: Code
  url: https://osf.io/f4r5v/
- icon: table
  text: Data
  url: https://osf.io/kr2cd/
citation:
  type: article-journal
  container-title: JAMA Pediatrics
  doi: 10.1001/jamapediatrics.2024.1832
  url: https://doi.org/10.1001/jamapediatrics.2024.1832
  page: advance online publication
---

### Importance

Health professionals routinely recommend "intensive interventions" (i.e., 20-40 hours per week) for autistic children. However, primary research backing this recommendation is sparse and plagued by methodological flaws. 

### Objective

We examined whether different metrics of intervention amount are associated with intervention effects on any developmental domain for young autistic children.

### Data Sources

We used a large corpus of studies $(n = 144)$ taken from a recent meta-analysis (with a search date of November 2021) of early interventions for autistic children. 

### Study Selection

Studies were eligible if they reported a quasi-experimental or randomized controlled trial testing the effects of a nonpharmacological intervention on any outcome in participant samples comprising >50% autistic children age 8 or younger. 

### Data Extraction and Synthesis

Data were independently extracted by multiple coders. We constructed meta-regression models to determine whether each index of intervention amount was associated with effect sizes for each intervention type, while controlling for outcome domain, outcome proximity, age of participants, study design, and risk of detection bias. 

### Main Outcomes and Measures

The primary predictor of interest was intervention amount, quantified using three different metrics (daily intensity, duration, and cumulative intensity). The primary outcomes of interest were gains in any developmental domain, quantified by Hedges $g$ effect sizes.

### Results

None of the meta-regression models evidenced a significant, positive association between any index of intervention amount and intervention effect size when considered within intervention type. 

### Conclusions and Relevance

Our findings do not support the assertion that intervention effects increase with increasing amounts of intervention. Health professionals recommending supports should be advised that there is little robust evidence supporting the provision of "intensive" intervention. Our prior meta-analyses suggest that some interventions have the potential to improve some outcomes for autistic children during early childhood. The present results, however, suggest that providing more of such interventions will not necessarily result in larger effects on outcomes of interest. There is a pressing need for future primary research to be designed and conducted in a manner that allows us to determine the most supportive amounts of interventions by child characteristics, intervention type, and the outcomes targeted by the intervention. 

