---
title: Equivalences between ad hoc strategies and meta-analytic models for dependent effect sizes
author:
- James E. Pustejovsky
- Man Chen
date: 2024-03-07T00:00:00
publish_date: 2024-03-07T00:00:00
publication_type: Journal article
publication: Journal of Educational and Behavioral Statistics
pages: advance online publication
categories:
- meta-analysis
- meta-regression
- dependent effect sizes
- robust variance estimation
links:
- text: Journal
  url: https://doi.org/10.3102/10769986241232524
  faicon: newspaper
- text: Supplementary materials
  url: https://osf.io/9u52e/
- faicon: lock-open
  text: Pre-Print
  url: https://osf.io/preprints/metaarxiv/pw54r/
- faicon: code
  text: Code
  url: https://osf.io/9u52e/
- faicon: table
  text: Data
  url: https://osf.io/9u52e/

---


Meta-analyses of educational research findings frequently involve statistically dependent effect size estimates. Meta-analysts have often addressed dependence issues using ad hoc approaches that involve modifying the data to conform to the assumptions of models for independent effect size estimates, such as aggregating estimates to obtain one summary estimate per study, conducting separate analyses of distinct subgroups of estimates, or combinations thereof. We demonstrate that these ad hoc approaches correspond exactly to certain multivariate models for dependent effect sizes. Specifically, we describe classes of multivariate random effects models that have likelihoods equivalent to those of models for effect sizes that have been averaged by study, classified into subgroups, or both. The equivalence also applies to robust variance estimation methods.

