project:
  type: website

website:
  title: "James E. Pustejovsky"
  site-url: https://jepusto.com
  description: "Education Statistics and Meta-Analysis"
  twitter-card: true
  navbar:
    left:
      - text: CV
        href: /files/Pustejovsky-CV.pdf
      - href: people/index.qmd
      - href: posts/index.qmd
      - working-papers.qmd
      - href: publication/index.qmd
      - href: presentations/index.qmd
      - href: software/index.qmd
      - href: teaching/index.qmd
      - contact.qmd
    right:
      - icon: rss
        href: index.xml
format:
  html:
    theme: sandstone
    linkcolor: "#1f67db"
    css: styles.css
