project:
  type: website

website:
  title: "James E. Pustejovsky"
  navbar:
    left:
      - text: CV
        url: /files/Pustejovsky-CV.pdf
      - posts.qmd
      - presentations.qmd
      - people.qmd
      - software.qmd
      - teaching.qmd

format:
  html:
    theme: sandstone
    linkcolor: "#1f67db"
    css: styles.css
