project:
  type: website

website:
  title: "James E. Pustejovsky"
  site-url: https://jepusto.com
  repo-url: https://github.com/jepusto/jepusto-quarto
  description: "Education Statistics and Meta-Analysis"
  twitter-card: true
  open-graph: true
  navbar:
    left:
      - text: CV
        href: /files/Pustejovsky-CV.pdf
      - href: people/index.qmd
      - href: posts/index.qmd
      - working-papers.qmd
      - text: Publications
        href: publication/index.qmd
      - href: presentations/index.qmd
      - href: software/index.qmd
      - href: teaching/index.qmd
      - contact.qmd
    right:
      - icon: rss
        href: index.xml
format:
  html:
    theme: 
      - sandstone
      - custom.scss
    linkcolor: "#3f51b5"
    fontcolor: "#313131"
    smooth-scroll: true
