project:
  type: website

website:
  title: "James E. Pustejovsky"
  navbar:
    left:
      - posts.qmd
      - people.qmd
      - teaching.qmd

format:
  html:
    theme: sandstone
    linkcolor: "#1f67db"
    css: styles.css
