---
title: A d-statistic for single-case designs that is equivalent to the usual between-groups d-statistics
authors:
- William R. Shadish
- Larry V. Hedges
- admin
- Jonathan G. Boyajian
- Kristynn J. Sullivan
- Alma Andrade
- Jeannette Barrientos
date: 2013-07-18T00:00:00
publish_date: 2013-07-18T00:00:00
publication_type: Journal article
publication: Neuropsychological Rehabilitation
volume: 24
issue: 3-4
pages: 528-553
categories:
- single-case design
- design-comparable SMD
- effect size
links:
- text: Journal
  url: https://doi.org/10.1080/09602011.2013.819021
  icon: fa newspaper

---
{{< include '../_publication_header.qmd' >}}


We describe a standardised mean difference statistic (d) for single-case designs that is equivalent to the usual d in between-groups experiments. We show how it can be used to summarise treatment effects over cases within a study, to do power analyses in planning new studies and grant proposals, and to meta-analyse effects across studies of the same question. We discuss limitations of this d-statistic, and possible remedies to them. Even so, this d-statistic is better founded statistically than other effect size measures for single-case design, and unlike many general linear model approaches such as multilevel modelling or generalised additive models, it produces a standardised effect size that can be integrated over studies with different outcome measures. SPSS macros for both effect size computation and power analysis are available.

