---
title: A meta-analytic review of religious or spiritual involvement and social health among cancer patients
authors:
- Allen C. Sherman
- Thomas V. Merluzzi
- James E. Pustejovsky
- Crystal L. Park
- Logan George
- George Fitchett
- Heather S. Jim
- Alexis R. Munoz
- Suzanne C. Danhauer
- Mallory A. Snyder
- John A. Salsman
date: 2015-08-10T00:00:00
publish_date: 2015-08-10T00:00:00
publication_type: Journal article
publication: Cancer
volume: 121
issue: 21
pages: 3779-3788
categories:
- cancer
- correlation
- meta-analysis
- religion/spirituality
- social health
- systematic review
links:
- text: Journal
  url: http://doi.org/10.1002/cncr.29352
  icon: fa newspaper

---
{{< include '../_publication_header.qmd' >}}


Religion and spirituality (R/S) play an important role in the daily lives of many cancer patients. There has been great interest in determining whether R/S factors are related to clinically relevant health outcomes. In this meta-analytic review, the authors examined associations between dimensions of R/S and social health (eg, social roles and relationships). A systematic search of the PubMed, PsycINFO, Cochrane Library, and Cumulative Index to Nursing and Allied Health Literature databases was conducted, and data were extracted by 4 pairs of investigators. Bivariate associations between specific R/S dimensions and social health outcomes were examined in a meta-analysis using a generalized estimating equation approach. In total, 78 independent samples encompassing 14,277 patients were included in the meta-analysis. Social health was significantly associated with overall R/S (Fisher z effect size = .20; P < .001) and with each of the R/S dimensions (affective R/S effect size = 0.31 [P < .001]; cognitive R/S effect size = .10 [P < .01]; behavioral R/S effect size = .08 [P < .05]; and ‘other’ R/S effect size = .13 [P < .001]). Within these dimensions, specific variables tied to socialhealth included spiritual well being, spiritual struggle, images of God, R/S beliefs, and composite R/S measures (all P values < .05). None of the demographic or clinical moderating variables examined were significant. Results suggest that several R/S dimensions are modestly associated with patients' capacity to maintain satisfying social roles and relationships in the context of cancer. Further research is needed to examine the temporal nature of these associations and the mechanisms that underlie them.

