---
title: 'Meta-Analysis with robust variance estimation: Expanding the range of working
  models'
author:
- name:
    given: James E.
    family: Pustejovsky
- name:
    given: Elizabeth
    family: Tipton
date: 2022-04-01T00:00:00
categories:
- meta-analysis
- meta-regression
- dependent effect sizes
- robust variance estimation
image-alt: Decision-tree for selecting a working model for use with RVE meta-regression
links:
- text: Journal
  url: https://doi.org/10.1007/s11121-021-01246-3
  icon: newspaper
- text: Supplementary materials
  url: https://osf.io/nyv4u/
- icon: unlock-fill
  text: Pre-Print
  url: https://osf.io/preprints/metaarxiv/vyfcj/
- icon: file-easel
  text: Slides
  url: /files/ESMARConf2021-RVE-with-clubSandwich.pdf
- icon: code-slash
  text: Code
  url: https://osf.io/z27wt/
- icon: table
  text: Data
  url: https://osf.io/xpmjk/
- icon: youtube
  text: Video
  url: https://youtu.be/Q9Nce5pxebY?t=66
citation:
  type: article-journal
  container-title: Prevention Science
  url: https://doi.org/10.1007/s11121-021-01246-3
  doi: 10.1007/s11121-021-01246-3
  volume: 23
  page: 425-438

---

In prevention science and related fields, large meta-analyses are common, and these analyses often involve dependent effect size estimates. Robust variance estimation (RVE) methods provide a way to include all dependent effect sizes in a single meta-regression model, even when the nature of the dependence is unknown. RVE uses a working model of the dependence structure, but the two currently available working models are limited to each describing a single type of dependence. Drawing on flexible tools from multivariate meta-analysis, this paper describes an expanded range of working models, along with accompanying estimation methods, which offer benefits in terms of better capturing the types of data structures that occur in practice and improving the efficiency of meta-regression estimates. We describe how the methods can be implemented using existing software (the 'metafor' and 'clubSandwich' packages for R) and illustrate the approach in a meta-analysis of randomized trials examining the effects of brief alcohol interventions for adolescents and young adults.


