---
title: 'Single case design research in Special Education: Next generation standards
  and considerations'
author:
- name:
    given: Jennifer R.
    family: Ledford
- name:
    given: Joseph
    family: Lambert
- name:
    given: James E.
    family: Pustejovsky
- name:
    given: Kathleen N.
    family: Zimmerman
- name:
    given: Nicole
    family: Hollins
- name:
    given: Erin E.
    family: Barton
date: 2022-11-22T00:00:00
categories:
- single-case design
- meta-analysis
- effect size
links:
- text: Journal
  url: https://doi.org/10.1177/00144029221137656
  icon: newspaper
- text: Supplementary materials
  url: https://osf.io/bt9hf/
- icon: unlock-fill
  text: Pre-Print
  url: https://osf.io/e98nw/
citation:
  type: article-journal
  container-title: Exceptional Children
  url: https://doi.org/10.1177/00144029221137656
  doi: 10.1016/j.jsp.2018.02.003
  volume: 89
  issue: 4
  page: 379-396

---

Single case design has a long history of use for assessing intervention effectiveness for children with disabilities. Although these designs have been widely employed for more than 50 years, recent years have been especially dynamic in terms of growth in the use of single case design and application of standards designed to improve the validity and applicability of findings. This growth expanded possibilities and inspired new questions about the contributions this methodology can make to generalizable knowledge about intervention in special education. In this paper, we discuss and extend previous standards for studies using single case designs (i.e., Horner et al., 2005). We identify new suggestions for internal validity, generality and acceptability, and reporting. We also provide considerations for single case synthesis and discuss the complexities of assessing accumulating evidence for a given practice.


