---
title: Small-sample adjustments for tests of moderators and model fit using robust
  variance estimation in meta-regression
author:
- name:
    given: Elizabeth
    family: Tipton
- name:
    given: James E.
    family: Pustejovsky
date: 2015-12-15T00:00:00
categories:
- meta-analysis
- meta-regression
- robust variance estimation
- small-sample
links:
- text: Journal
  url: http://doi.org/10.3102/1076998615606099
  icon: newspaper
- text: R package
  url: https://CRAN.R-project.org/package=clubSandwich
  icon: box2
- icon: unlock-fill
  text: Pre-Print
  url: /files/Tipton-Pustejovsky-F-tests-with-RVE-May-2015.pdf
citation:
  type: article-journal
  container-title: Journal of Educational and Behavioral Statistics
  url: http://doi.org/10.3102/1076998615606099
  doi: 10.1016/j.jsp.2018.02.003
  volume: 40
  issue: 6
  page: 604-634

---

Meta-analyses often include studies that report multiple effect sizes based on a common pool of subjects or that report effect sizes from several samples that were treated with very similar research protocols. The inclusion of such studies introduces dependence among the effect size estimates. When the number of studies is large, robust variance estimation (RVE) provides a method for pooling dependent effects, even when information on the exact dependence structure is not available. When the number of studies is small or moderate, however, test statistics and confidence intervals based on RVE can have inflated Type I error. This article describes and investigates several small-sample adjustments to F-statistics based on RVE. Simulation results demonstrate that one such test, which approximates the test statistic using Hotelling’s T-squared distribution, is level-α and uniformly more powerful than the others. An empirical application demonstrates how results based on this test compare to the large-sample F-test.


