---
title: Power approximations for overall average effects in meta-analysis of dependent
  effect sizes
author:
- name:
    given: Mikkel H.
    family: Vembye
- name:
    given: James E.
    family: Pustejovsky
- name:
    given: Terri D.
    family: Pigott
date: 2022-10-17T00:00:00
categories:
- power
- meta-analysis
- dependent effect sizes
- robust variance estimation
image-alt: Power difference between approximated and true (simulated) power versus
  approximated power for the C(H)E working models, across different methods of sampling
  study characteristics.
links:
- text: Journal
  url: https://doi.org/10.3102/10769986221127379
  icon: newspaper
- text: Supplementary materials
  url: https://osf.io/q84dv/
- text: Correction
  url: https://doi.org/10.3102/10769986231207878
- text: R package
  url: https://mikkelvembye.github.io/POMADE/
  icon: box2
- icon: unlock-fill
  text: Pre-Print
  url: https://osf.io/preprints/metaarxiv/6tp9y/
- icon: code-slash
  text: Code
  url: https://osf.io/yhkq4/
citation:
  type: article-journal
  container-title: Journal of Educational and Behavioral Statistics
  url: https://doi.org/10.3102/10769986221127379
  doi: 10.1016/j.jsp.2018.02.003
  volume: 48
  issue: 1
  page: 70-102
---

Meta-analytic models for dependent effect sizes have grown increasingly sophisticated over the last few decades, which has created challenges for a priori power calculations. We introduce power approximations for tests of average effect sizes based upon several common approaches for handling dependent effect sizes. In a Monte Carlo simulation, we show that the new power formulas can accurately approximate the true power of meta-analytic models for dependent effect sizes. Lastly, we investigate the Type I error rate and power for several common models, finding that tests using robust variance estimation provide better Type I error calibration than tests with model-based variance estimation. We consider implications for practice with respect to selecting a working model and an inferential approach.


