---
title: 'Effects of psychosocial interventions on meaning and purpose in adults with cancer: A systematic review and meta-analysis'
author:
- Crystal L. Park
- James E. Pustejovsky
- Kelly Trevino
- Allen C. Sherman
- Craig Esposito
- Mark Berendsen
- John A. Salsman
date: 2019-04-29T00:00:00
publish_date: 2019-04-29T00:00:00
publication_type: Journal article
publication: Cancer
volume: 125
issue: 14
pages: 2383-2393
categories:
- cancer
- meaning and purpose
- meta-analysis
- psycho-social intervention
- systematic review
links:
- text: Journal
  url: https://doi.org/10.1002/cncr.32078
  icon: newspaper

---


Meaning and purpose in life are associated with the mental and physical health of patients with cancer and survivors and also constitute highly valued outcomes in themselves. Because meaning and purpose are often threatened by a cancer diagnosis and treatment, interventions have been developed to promote meaning and purpose. The present meta-analysis of randomized controlled trials (RCTs) evaluated effects of psychosocial interventions on meaning/purpose in adults with cancer and tested potential moderators of intervention effects. Six literature databases were systematically searched to identify RCTs of psychosocial interventions in which meaning or purpose was an outcome. Using Preferred Reporting Items for Systematic Reviews and Meta‐Analyses guidelines, rater pairs extracted and evaluated data for quality. Findings were synthesized across studies with standard meta‐analytic methods, including meta‐regression with robust variance estimation and risk-of-bias sensitivity analysis. Twenty-nine RCTs were identified, and they encompassed 82 treatment effects among 2305 patients/survivors. Psychosocial interventions were associated with significant improvements in meaning/purpose (g = 0.37; 95% CI, 0.22-0.52; P < .0001). Interventions designed to enhance meaning/purpose (g = 0.42; 95% CI, 0.24-0.60) demonstrated significantly higher effect sizes than those targeting other primary outcomes (g = 0.18; 95% CI, 0.09-0.27; P = .009). Few other intervention, clinical, or demographic characteristics tested were significant moderators. In conclusion, the results suggest that psychosocial interventions are associated with small to medium effects in enhancing meaning/purpose among patients with cancer, and the benefits are comparable to those of interventions designed to reduce depression, pain, and fatigue in patients with cancer. Methodological concerns include small samples and ambiguity regarding allocation concealment. Future research should focus on explicitly meaning-centered interventions and identify optimal treatment or survivorship phases for implementation.

