---
title: 'Design-comparable effect sizes in multiple baseline designs: A general modeling framework'
authors:
- admin
- Larry V. Hedges
- William R. Shadish
date: 2014-10-01T00:00:00
publish_date: 2014-10-01T00:00:00
publication_type: Journal article
publication: Journal of Educational and Behavioral Statistics
volume: 39
issue: 5
pages: 368-393
categories:
- single-case design
- design-comparable SMD
- effect size
- hierarchical models
links:
- text: Supplementary materials
  url: /files/Effect-sizes-in-multiple-baseline-designs-Simulation-results.pdf
- text: Journal
  url: https://doi.org/10.3102/1076998614547577
  icon: fa newspaper
- text: R package
  url: https://CRAN.R-project.org/package=scdhlm
  icon: fa gift
- text: Web app
  url: https://jepusto.shinyapps.io/scdhlm/
  icon: fa tablet-screen-button
- icon: fa lock-open
  text: Pre-Print
  url: /files/Effect-sizes-in-multiple-baseline-designs-JEBS.pdf

---
{{< include '../_publication_header.qmd' >}}


In single-case research, the multiple baseline design is a widely used approach for evaluating the effects of interventions on individuals. Multiple baseline designs involve repeated measurement of outcomes over time and the controlled introduction of a treatment at different times for different individuals. This article outlines a general framework for defining effect sizes in multiple baseline designs that are directly comparable to the standardized mean difference from a between-subjects randomized experiment. The target, design-comparable effect size parameter can be estimated using restricted maximum likelihood together with a small sample correction analogous to Hedges’s g. The approach is demonstrated using hierarchical linear models that include baseline time trends and treatment-by-time interactions. A simulation compares the performance of the proposed estimator to that of an alternative, and an application illustrates the model-fitting process.

