<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.552">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="James E. Pustejovsky">
<meta name="dcterms.date" content="2020-06-09">

<title>James E. Pustejovsky - Weighting in multivariate meta-analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="James E. Pustejovsky - Weighting in multivariate meta-analysis">
<meta property="og:description" content="Education Statistics and Meta-Analysis">
<meta property="og:site_name" content="James E. Pustejovsky">
<meta name="twitter:title" content="James E. Pustejovsky - Weighting in multivariate meta-analysis">
<meta name="twitter:description" content="Education Statistics and Meta-Analysis">
<meta name="twitter:card" content="summary">
<meta name="citation_title" content="Weighting in multivariate meta-analysis">
<meta name="citation_author" content="James E. Pustejovsky">
<meta name="citation_publication_date" content="2020-06-09">
<meta name="citation_cover_date" content="2020-06-09">
<meta name="citation_year" content="2020">
<meta name="citation_online_date" content="2020-06-09">
<meta name="citation_fulltext_html_url" content="https://mellifluous-buttercream-e2edd2.netlify.app/posts/weighting-in-multivariate-meta-analysis">
<meta name="citation_language" content="en">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">James E. Pustejovsky</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../files/Pustejovsky-CV.pdf"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../people/index.html"> 
<span class="menu-text">People</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../posts/index.html"> 
<span class="menu-text">Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../working-papers.html"> 
<span class="menu-text">Working Papers</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../publication/index.html"> 
<span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../presentations/index.html"> 
<span class="menu-text">Presentations</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../software/index.html"> 
<span class="menu-text">Software</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../teaching/index.html"> 
<span class="menu-text">Teaching</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../contact.html"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bi-rss" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-rss" role="img">
</i> 
 <span class="menu-text"></span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-bi-rss">    
        <li>
    <a class="dropdown-item" href="../../posts/index.xml"><i class="bi bi-rss" role="img">
</i> 
 <span class="dropdown-text">Posts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../publication/index.xml"><i class="bi bi-rss" role="img">
</i> 
 <span class="dropdown-text">Publications</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Weighting in multivariate meta-analysis</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">meta-analysis</div>
                <div class="quarto-category">weighting</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>James E. Pustejovsky </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">June 9, 2020</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#a-little-background" id="toc-a-little-background" class="nav-link active" data-scroll-target="#a-little-background"><span class="header-section-number">1</span> A little background</a></li>
  <li><a href="#a-multivariate-meta-analysis" id="toc-a-multivariate-meta-analysis" class="nav-link" data-scroll-target="#a-multivariate-meta-analysis"><span class="header-section-number">2</span> A multivariate meta-analysis</a></li>
  <li><a href="#equally-precise-effect-size-estimates" id="toc-equally-precise-effect-size-estimates" class="nav-link" data-scroll-target="#equally-precise-effect-size-estimates"><span class="header-section-number">3</span> Equally precise effect size estimates</a></li>
  <li><a href="#a-computational-example" id="toc-a-computational-example" class="nav-link" data-scroll-target="#a-computational-example"><span class="header-section-number">4</span> A computational example</a></li>
  <li><a href="#now-without-compound-symmetry" id="toc-now-without-compound-symmetry" class="nav-link" data-scroll-target="#now-without-compound-symmetry"><span class="header-section-number">5</span> Now without compound symmetry</a></li>
  <li><a href="#what-about-meta-regression" id="toc-what-about-meta-regression" class="nav-link" data-scroll-target="#what-about-meta-regression"><span class="header-section-number">6</span> What about meta-regression?</a></li>
  <li><a href="#and-beyond" id="toc-and-beyond" class="nav-link" data-scroll-target="#and-beyond"><span class="header-section-number">7</span> And beyond!</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>One common question about multivariate/multi-level meta-analysis is how such models assign weight to individual effect size estimates. When a version of the question came up recently on the <a href="https://stat.ethz.ch/pipermail/r-sig-meta-analysis/2020-June/002149.html">R-sig-meta-analysis listserv</a>, Dr.&nbsp;Wolfgang Viechtbauer offered a <a href="http://www.metafor-project.org/doku.php/tips:weights_in_rma.mv_models">whole blog post</a> in reply, demonstrating how weights work in simpler fixed effect and random effects meta-analysis and then how things get more complicated in multivariate models. I started thumb-typing my own reply as well, but then decided it would be better to write up a post so that I could use a bit of math notation (and to give my thumbs a break). So, in this post I’ll try to add some further intuition on how weights work in certain multivariate meta-analysis models. Most of the discussion will apply to models that include multiple level of random effects, but no predictors. I’ll also comment briefly on meta-regression models with only study-level predictor variables, and finally give some pointers to work on more complicated models.</p>
<section id="a-little-background" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> A little background</h1>
<p>It’s helpful to start by looking briefly at the basic fixed effect and random effects models, assuming that we’ve got a set of studies that each contribute a single effect size estimate so everything’s independent. Letting <span class="math inline">\(T_j\)</span> be the effect size from study <span class="math inline">\(j\)</span>, with sampling variance <span class="math inline">\(V_j\)</span>, both for <span class="math inline">\(j = 1,...,k\)</span>, the basic random effects model is: <span class="math display">\[
T_j = \mu + \eta_j + e_j
\]</span> where <span class="math inline">\(\mu\)</span> is the overall average effect size, <span class="math inline">\(v_j\)</span> is a random effect with variance <span class="math inline">\(\text{Var}(\eta_j) = \tau^2\)</span> and <span class="math inline">\(e_j\)</span> is a sampling error with known variance <span class="math inline">\(V_j\)</span>. The first step in estimating this model is to estimate <span class="math inline">\(\tau^2\)</span>. There’s lots of methods for doing so, but let’s not worry about those details—just pick one and call the estimate <span class="math inline">\(\hat\tau^2\)</span>. Then, to estimate <span class="math inline">\(\mu\)</span>, we take a weighted average of the effect size estimates: <span class="math display">\[
\hat\mu = \frac{1}{W} \sum_{j=1}^k w_j T_j, \qquad \text{where} \quad W = \sum_{j=1}^k w_j.
\]</span> The weights used in the weighted average are chosen to make the overall estimate as precise as possible (i.e., having the smallest possible sampling variance or standard error). Mathematically, the best possible weights are <strong><em>inverse variance</em></strong> weights, that is, setting the weight for each effect size estimate proportional to the inverse of how much variance there is in each estimate. With inverse variance weights, larger studies with more precise effect size estimates will tend to get more weight and smaller, noisier studies will tend to get less weight.</p>
<p>In the basic random effects model, the weights for each study are proportional to <span class="math display">\[
w_j = \frac{1}{\hat\tau^2 + V_j},
\]</span> for <span class="math inline">\(j = 1,...,k\)</span>. The denominator term here includes both the (estimated) between-study heterogeneity and the sampling variance because both terms contribute to how noisy the effect size estimate is. In the fixed effect model, we ignore between-study heterogeneity so the weights are inversely proportional to the sampling variances, with <span class="math inline">\(w_j = 1 / V_j\)</span>. In the random effects model, larger between-study heterogeneity will make the weights closer to equal, while smaller between-study heterogeneity will lead to weights that tend to emphasize larger studies with more precise estimates. In the remainder, I’ll show that there are some similar dynamics at work in a more complicated, multivariate meta-analysis model.</p>
</section>
<section id="a-multivariate-meta-analysis" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> A multivariate meta-analysis</h1>
<p>Now let’s consider the case where some or all studies in our synthesis contribute more than one effect size estimate. Say that we have effect sizes <span class="math inline">\(T_{ij}\)</span>, where <span class="math inline">\(i = 1,...,n_j\)</span> indexes effect size estimates within study <span class="math inline">\(j\)</span> and <span class="math inline">\(j\)</span> indexes studies, for <span class="math inline">\(j = 1,...,k\)</span>. Say that effect size estimate <span class="math inline">\(T_{ij}\)</span> has sampling variance <span class="math inline">\(V_{ij}\)</span>, and there is some sampling correlation between effect sizes <span class="math inline">\(h\)</span> and <span class="math inline">\(i\)</span> within study <span class="math inline">\(j\)</span>, denoted <span class="math inline">\(r_{hij}\)</span>.</p>
<p>There are many models that a meta-analyst might consider for this data structure. A fairly common one would be a model that includes random effects not only for between-study heterogeneity (as in the basic random effects model) but also random effects capturing within-study heterogeneity in true effect sizes. Let me write this model heirarchically, as <span class="math display">\[
\begin{align}
T_{ij} &amp;= \theta_j + \nu_{ij} + e_{ij} \\
\theta_j &amp;= \mu + \eta_j
\end{align}
\]</span> In the first line of the model, <span class="math inline">\(\theta_j\)</span> denotes the average effect size parameter for study <span class="math inline">\(j\)</span>, <span class="math inline">\(\nu_{ij}\)</span> captures within-study heterogeneity in the true effect size parameters and <span class="math inline">\(e_{ij}\)</span> is a sampling error. Above, I’ve assumed that we know the structure of the sampling errors, so <span class="math inline">\(\text{Var}(e_{ij}) = V_{ij}\)</span> and <span class="math inline">\(\text{Cov}(e_{hj}, e_{ij}) = r_{hij} \sqrt{V_{hj} V_{ij}}\)</span>. Let’s also denote the within-study variance as <span class="math inline">\(\omega^2\)</span>, so <span class="math inline">\(\text{Var}(\nu_{ij}) = \omega^2\)</span>. In the second line of the model, <span class="math inline">\(\mu\)</span> is still the overall average effect size across all studies and effect sizes within studies and <span class="math inline">\(\eta_j\)</span> is a between-study error, with <span class="math inline">\(\text{Var}(\eta_j) = \tau^2\)</span>, capturing the degree of heterogeneity in the <em>average</em> effect sizes (the <span class="math inline">\(\theta_j\)</span>’s) across studies.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>One thing to note about this model is that it treats all of the effect sizes as coming from a population with a common mean <span class="math inline">\(\mu\)</span>. Some statisticians might object to calling it a multivariate model because we’re not distinguishing averages for different dimensions (or variates) of the effect sizes. To this I say: whatev’s, donkey! I’m calling it multivariate because you have to use the <code>rma.mv()</code> function from the <code>metafor</code> package to estimate it. I will acknowledge, though, that there will often be reason to use more complicated models, for example by replacing the overall average <span class="math inline">\(\mu\)</span> with some meta-regression <span class="math inline">\(\mathbf{x}_{ij} \boldsymbol\beta\)</span>. That’s a discussion for another day. For now, we’re only going to consider the model with an overall average effect size parameter <span class="math inline">\(\mu\)</span>. The question is, <strong><em>how do the individual effect size estimates <span class="math inline">\(T_{ij}\)</span> contribute to the estimate of this overall average effect?</em></strong></p>
</section>
<section id="equally-precise-effect-size-estimates" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Equally precise effect size estimates</h1>
<p>To make some headway, it is helpful to first consider an even more specific model where, within a given study, all effect size estimates are equally precise and equally correlated. In particular, let’s assume that for each study <span class="math inline">\(j\)</span>, the sampling variances are all equal, with <span class="math inline">\(V_{ij} = V_j\)</span> for <span class="math inline">\(i = 1,...,n_j\)</span>, and the correlations between the sampling errors are also all equal, with <span class="math inline">\(r_{hij} = r_j\)</span> for <span class="math inline">\(h,i = 1,...,n_j\)</span>.</p>
<p>These assumptions might not be all that far-fetched. Within a given study, if the effect size estimates are for different measures of a common construct, it’s not unlikely that they would all be based on similar sample sizes (+/- a bit of item non-response). It might be a bit less likely if the effect size estimates are for treatment effects from different follow-up times (since drop-out/non-response tends to increase over time) or different treatment groups compared to a common control group—but still perhaps not entirely unreasonable. Further, it’s rather <em>uncommon</em> to have good information about the correlations between effect size estimates from a given study (because primary studies don’t often report all of the information needed to calculate these correlations). In practice, meta-analysts might need to simply <a href="../..\posts/imputing-covariance-matrices-for-multi-variate-meta-analysis/">make a rough guess about the correlations</a> and then use robust variance estimation and/or sensitivity analysis to check themselves. And if we’re just ball-parking, then we’ll probably assume a single correlation for all of the studies.</p>
<p>The handy thing about this particular scenario is that, because all of the effect size estimates within a study are equally precise and equally correlated, the most efficient way to estimate an average effect for a given study is to <strong><em>just take the simple average</em></strong> (and, intuitively, this seems like the only sensible thing to do). To be precise, consider how we would estimate <span class="math inline">\(\theta_j\)</span> for a given study <span class="math inline">\(j\)</span>. The most precise possible estimate is simply <span class="math display">\[
\hat\theta_j = \frac{1}{n_j} \sum_{i=1}^{n_j} T_{ij}.
\]</span> And we could do the same for each of the other studies, <span class="math inline">\(j = 1,...,k\)</span>. It turns out that the estimate of the overall average effect size is a weighted average of these study-specific average effect sizes: <span class="math display">\[
\hat\mu = \frac{1}{W} \sum_{j=1}^k w_j \hat\theta_j,
\]</span> for some weights <span class="math inline">\(w_1,...,w_k\)</span>. But what are these weights? Just like in the basic random effects model, they are inverse-variance weights. It’s just that the variance is a little bit more complicated.</p>
<p>Consider how precise each of the study-specific estimates are, relative to the true effects in their respective studies. Conditional on the true effect <span class="math inline">\(\theta_j\)</span>, <span class="math display">\[
\text{Var}(\hat\theta_j | \theta_j) = \frac{1}{n_j}\left(\omega^2 + (n_j - 1) r_j V_j + V_j\right).
\]</span> Without conditioning on <span class="math inline">\(\theta_j\)</span>, the variance of the <span class="math inline">\(\hat\theta_j\)</span> estimates also includes a term for variation in the true study-specific average effect sizes, becoming <span class="math display">\[
\text{Var}(\hat\theta_j) = \tau^2 + \frac{1}{n_j}\left(\omega^2 + (n_j - 1) r_j V_j + V_j\right).
\]</span> The weights used in estimating <span class="math inline">\(\mu\)</span> are the inverse of this quantity: <span class="math display">\[
w_j = \frac{1}{\tau^2 + \frac{1}{n_j}\left(\omega^2 + (n_j - 1) r_j V_j + V_j\right)}.
\]</span> Within a study, each individual effect size gets an <span class="math inline">\(n_j^{th}\)</span> of this study-level weight. We can therefore write the overall average as <span class="math display">\[
\hat\mu = \frac{1}{W} \sum_{j=1}^k \sum_{i=1}^{n_j} w_{ij} T_{ij},
\]</span> where <span class="math display">\[
w_{ij} = \frac{1}{n_j \tau^2 + \omega^2 + (n_j - 1) r_j V_j + V_j}.
\]</span></p>
<p>There are several things worth noting about this expression for the weights. First, suppose that there is little between-study or within-study heterogeneity, so <span class="math inline">\(\tau^2\)</span> and <span class="math inline">\(\omega^2\)</span> are both close to zero. Then the weights are driven by the number of effect sizes within the study (<span class="math inline">\(n_j\)</span>), the sampling variance of those effect sizes (<span class="math inline">\(V_j\)</span>) and their correlation <span class="math inline">\(r_j\)</span>. If <span class="math inline">\(r_j\)</span> is near one, then averaging together a bunch of highly correlated estimates doesn’t improve precision much, relative to just using one of the effect sizes. The study-specific average effect estimate will therefore have variance close to <span class="math inline">\(V_j\)</span> (i.e., the variance of a single effect size estimate). If <span class="math inline">\(r_j\)</span> is below one, then averaging yields a more precise estimate than any of the individual effect sizes, and averaging together more effect sizes will yield a more precise estimate at the study level. If the assumed correlations are reasonably accurate, the weights used in the multi-variate meta-analysis will appropriately take into account the number of effect sizes within each study and the precision of those effect sizes.</p>
<p>Second, now suppose that there is no between-study heterogeneity (<span class="math inline">\(\tau^2 = 0\)</span>) but there is positive within-study heterogeneity. Larger degrees of within-study heterogeneity will tend to equalize the weights <em>at the effect size level</em>, regardless of how effect size estimates are nested within studies. When there is within-study heterogeneity, averaging together a bunch of estimates will yield a more precise estimate of study-specific average effects. Therefore, when <span class="math inline">\(\omega^2\)</span> is larger, studies with more effect sizes will tend to get a relatively larger share of the weight.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>Third and finally, between-study heterogeneity will tend to equalize the weights at the study level, so that the overall average is pulled closer to a simple average of the study-specific average effects. This works very much like in basic random effects meta-analysis, where increased heterogeneity will lead to weights that are closer to equal and an average effect size estimate that is closer to a simple average.</p>
</section>
<section id="a-computational-example" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> A computational example</h1>
<p>I think it’s useful to verify algebraic results like the ones I’ve given above by checking that you can reproduce them with real data. I’ll use the <code>corrdat</code> dataset from the <code>robumeta</code> package for illustration. The dataset has one duplicated row in it (I have no idea why!), which I’ll remove before analyzing further.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(corrdat, <span class="at">package =</span> <span class="st">"robumeta"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>corrdat <span class="ot">&lt;-</span> </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  corrdat <span class="sc">%&gt;%</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(studyid, esid, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>This dataset included a total of 171 effect size estimates from 39 unique studies. For each study, between 1 and 18 eligible effect size estimates were reported. Here is a histogram depicting the number of studies by the number of reported effect size estimates:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>Here is the plot of the variances of each effect size versus the study IDs:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For most of the studies, the effect sizes have very similar sampling variances. One exception is study 9, where two of the effect sizes have variances of under 0.20 and the other two effect sizes have variances in excess of 0.35. Another exception is study 30, which has one effect size with much larger variance than the others.</p>
<p>Just for sake of illustration, I’m going to <em>enforce</em> my assumption that effect sizes have equal variances within each study by recomputing the sampling variances as the <em>average</em> sampling variance within each study. I will then impute a sampling variance-covariance matrix for the effect sizes, assuming a correlation of 0.7 for effects from the same study:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(clubSandwich)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>corrdat <span class="ot">&lt;-</span> </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  corrdat <span class="sc">%&gt;%</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(studyid) <span class="sc">%&gt;%</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">V_bar =</span> <span class="fu">mean</span>(var)) <span class="sc">%&gt;%</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>V_mat <span class="ot">&lt;-</span> <span class="fu">impute_covariance_matrix</span>(<span class="at">vi =</span> corrdat<span class="sc">$</span>V_bar, </span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">cluster =</span> corrdat<span class="sc">$</span>studyid,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">r =</span> <span class="fl">0.7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>With this variance-covariance matrix, I can then estimate the multivariate meta-analysis model:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(metafor)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>MVMA_fit <span class="ot">&lt;-</span> <span class="fu">rma.mv</span>(<span class="at">yi =</span> effectsize, <span class="at">V =</span> V_mat, </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">random =</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> studyid <span class="sc">/</span> esid,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> corrdat)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(MVMA_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Multivariate Meta-Analysis Model (k = 171; method: REML)

  logLik  Deviance       AIC       BIC      AICc   
-94.7852  189.5703  195.5703  204.9777  195.7149   

Variance Components:

            estim    sqrt  nlvls  fixed        factor 
sigma^2.1  0.0466  0.2159     39     no       studyid 
sigma^2.2  0.1098  0.3314    171     no  studyid/esid 

Test for Heterogeneity:
Q(df = 170) = 1141.4235, p-val &lt; .0001

Model Results:

estimate      se    zval    pval   ci.lb   ci.ub      
  0.2263  0.0589  3.8413  0.0001  0.1108  0.3417  *** 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Based on this model, between-study heterogeneity is estimated as <span class="math inline">\(\hat\tau = 0.216\)</span> and within-study heterogeneity is estimated as <span class="math inline">\(\hat\omega = 0.331\)</span>, both of which are quite high. The overall average effect size estimate is 0.226, with a standard error of 0.059.</p>
<p>I’ll first get the weights used in <code>rma.mv</code> to compute the overall average. The weights are represented as an <span class="math inline">\(N \times N\)</span> matrix. Taking the row or column sums, then rescaling by the total, gives the weight assigned to each effect size estimate:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>W_mat <span class="ot">&lt;-</span> <span class="fu">weights</span>(MVMA_fit, <span class="at">type =</span> <span class="st">"matrix"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>corrdat<span class="sc">$</span>w_ij_metafor <span class="ot">&lt;-</span> <span class="fu">colSums</span>(W_mat) <span class="sc">/</span> <span class="fu">sum</span>(W_mat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>To verify that the formulas above are correct, I’ll use them to directly compute weights:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fl">0.7</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>tau_sq <span class="ot">&lt;-</span> MVMA_fit<span class="sc">$</span>sigma2[<span class="dv">1</span>]</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>omega_sq <span class="ot">&lt;-</span> MVMA_fit<span class="sc">$</span>sigma2[<span class="dv">2</span>]</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>corrdat_weights <span class="ot">&lt;-</span> </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  corrdat <span class="sc">%&gt;%</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(studyid) <span class="sc">%&gt;%</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_j =</span> <span class="fu">n</span>(),</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">w_ij =</span> <span class="dv">1</span> <span class="sc">/</span> (n_j <span class="sc">*</span> tau_sq <span class="sc">+</span> omega_sq <span class="sc">+</span> (n_j <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> r <span class="sc">*</span> V_bar <span class="sc">+</span> V_bar)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">w_ij =</span> w_ij <span class="sc">/</span> <span class="fu">sum</span>(w_ij)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The weights I computed are perfectly correlated with the weights used <code>rma.mv</code>, as can be seen in the plot below.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(corrdat_weights, <span class="fu">aes</span>(w_ij, w_ij_metafor)) <span class="sc">+</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<p>If we remove the within-study random effect term from the model, the weights will be equivalent to setting <span class="math inline">\(\omega^2\)</span> to zero, but with a different estimate of <span class="math inline">\(\tau^2\)</span>.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>MVMA_no_omega <span class="ot">&lt;-</span> <span class="fu">rma.mv</span>(<span class="at">yi =</span> effectsize, <span class="at">V =</span> V_mat, </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">random =</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> studyid,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> corrdat)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>MVMA_no_omega</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Multivariate Meta-Analysis Model (k = 171; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed   factor 
sigma^2    0.0951  0.3084     39     no  studyid 

Test for Heterogeneity:
Q(df = 170) = 1141.4235, p-val &lt; .0001

Model Results:

estimate      se    zval    pval   ci.lb   ci.ub      
  0.2235  0.0619  3.6122  0.0003  0.1022  0.3448  *** 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Re-fitting the model with <code>rma.mv()</code> gives an between-study heterogeneity estimate of <span class="math inline">\(\hat\tau = 0.308\)</span> and an overall average effect size estimate of <span class="math inline">\(\hat\mu = 0\)</span>. Using this estimate, I’ll compute the weights based on the formula and then use those weights to determine the overall average effect size estimate.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>tau_sq <span class="ot">&lt;-</span> MVMA_no_omega<span class="sc">$</span>sigma2</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>corrdat_weights <span class="ot">&lt;-</span> </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  corrdat_weights <span class="sc">%&gt;%</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">w_ij_no_omega =</span> <span class="dv">1</span> <span class="sc">/</span> (n_j <span class="sc">*</span> tau_sq <span class="sc">+</span> (n_j <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> r <span class="sc">*</span> V_bar <span class="sc">+</span> V_bar),</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">w_ij_no_omega =</span> w_ij_no_omega <span class="sc">/</span> <span class="fu">sum</span>(w_ij_no_omega)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(corrdat_weights, <span class="fu">weighted.mean</span>(effectsize, <span class="at">w =</span> w_ij_no_omega))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2235231</code></pre>
</div>
</div>
<p>This matches the output of <code>rma.mv()</code>.</p>
<p>Here is a plot showing the weights of individual effect sizes for each study. In blue are the weights under the assumption that <span class="math inline">\(\omega^2 = 0\)</span>. In green are the weights allowing for <span class="math inline">\(\omega^2 &gt; 0\)</span>. It’s notable here that introducing the within-study heterogeneity term leads to pretty big changes in the weights for some studies. In particular, studies that have only a single effect size estimate (e.g., studys 7, 8, 22, 25, 28) lose <em>a lot</em> of weight when <span class="math inline">\(\omega^2 &gt; 0\)</span>. That’s partially because <span class="math inline">\(\omega^2\)</span> tends to pull weight towards studies with more effect sizes, and partially because of the change in the estimate of <span class="math inline">\(\tau^2\)</span>, which tends to equalize the weight assigned to each study.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Below is a plot illustrating the changes in study-level weights (i.e., aggregating the weight assigned to each study). The bar color corresponds to the number of effect size estimates in each study; light grey studies have just one effect size, while studies with more effect sizes are more intensly purple. The notable drops in weight for studies with a single effect size estimate (light grey) are visible here too. Studies with more effect sizes (e.g., studies 2, 15, 30, with dark purple bars) gain weight when we allow <span class="math inline">\(\omega^2\)</span> to be greater than zero.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="now-without-compound-symmetry" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Now without compound symmetry</h1>
<p>If we remove the restrictions that effect sizes from the same study have the same sampling variance and are equi-correlated, then the weights get a little bit more complicated. However, the general intuitions carry through. Let’s now consider the model with arbitrary sampling variance <span class="math inline">\(V_{ij}\)</span> and sampling correlations within studies <span class="math inline">\(r_{hij}\)</span>. The most efficient estimate of the study-specific average effect is now a <em>weighted</em> average, with weights that depend on both the variances and covariances of the effect size estimates within each study. Let <span class="math display">\[
\boldsymbol{\hat\Sigma}_j = \hat\omega^2 \mathbf{I}_j + \mathbf{V}_j,
\]</span> where <span class="math inline">\(\mathbf{I}_j\)</span> is an <span class="math inline">\(n_j \times n_j\)</span> identity matrix and <span class="math inline">\(\mathbf{V}_j\)</span> is the sampling variance-covariance matrix of the effect size estimates, with entry <span class="math inline">\((h,i)\)</span> equal to <span class="math inline">\(\left[\mathbf{V}_j\right]_{h,i} = r_{hij} \sqrt{V_{hj} V_{ij}}\)</span>. The estimate of the study-specific average effect size for study <span class="math inline">\(j\)</span> is still a weighted average: <span class="math display">\[
\hat\theta_j = \frac{\sum_{i=1}^{n_j} s_{ij} T_{ij}}{\sum_{i=1}^{n_j} s_{ij}},
\]</span> where <span class="math display">\[
s_{ij} = \displaystyle{\sum_{h=1}^{n_j} \left[\boldsymbol{\hat\Sigma}^{-1}\right]_{hi}},
\]</span> and <span class="math inline">\(\left[\boldsymbol{\hat\Sigma}^{-1}\right]_{hi}\)</span> denotes entry <span class="math inline">\((h,i)\)</span> in the inverse of the matrix <span class="math inline">\(\boldsymbol{\hat\Sigma}\)</span>. Let <span class="math inline">\(V^C_j\)</span> denote the variance of the study-specific average effect size estimate, conditional on the true <span class="math inline">\(\theta_j\)</span>: <span class="math display">\[
V^C_j = \text{Var}(\hat\theta_j | \theta_j) = \left(\sum_{i=1}^{n_j} s_{ij} \right)^{-1}
\]</span> The unconditional variance of <span class="math inline">\(\hat\theta_j\)</span> is then <span class="math display">\[
\text{Var}(\hat\theta_j) = \tau^2 + V^C_j.
\]</span> Because the overall average effect size estimate is (still) the inverse-variance weighted average, the weight assigned at the study level is equal to <span class="math display">\[
w_j = \frac{1}{\hat\tau^2 + V^C_j}
\]</span> and the weight assigned to individual effect sizes is <span class="math display">\[
w_{ij} = \frac{s_{ij} V^C_j}{\hat\tau^2 + V^C_j}.
\]</span> How do <span class="math inline">\(\omega^2\)</span> and <span class="math inline">\(\tau^2\)</span> affect these more general weights? The intuitions that I described earlier still mostly hold. Increasing <span class="math inline">\(\omega^2\)</span> will tend to equalize the weights at the effect size level (i.e., equalize the <span class="math inline">\(s_{ij}\)</span> across <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>), pulling weight towards studies with more effect size estimates. Increasing <span class="math inline">\(\tau^2\)</span> will tend to equalize the weights at the study-level.</p>
<p>One wrinkle with the more general form of the weights is that the effect-size level weights can sometimes be <em>negative</em> (i.e., negative <span class="math inline">\(s_{ij}\)</span>). This will tend to happen when the sampling variances within a study are discrepant, such as when one <span class="math inline">\(V_{ij}\)</span> is much smaller than the others in study <span class="math inline">\(j\)</span>, when the (assumed or estimated) sampling correlation is high, and when <span class="math inline">\(\omega^2\)</span> is zero or small. This is something that warrants further investigation.</p>
</section>
<section id="what-about-meta-regression" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> What about meta-regression?</h1>
<p>Some of the foregoing analysis also applies to models that include predictors. In particular, the formulas I’ve given for the weights will still hold for meta-regression models <strong><em>that include only study-level predictors</em></strong>. In other words, they work for models of the following form: <span class="math display">\[
T_{ij} = \mathbf{x}_j \boldsymbol\beta + \eta_j + \nu_{ij} + e_{ij},
\]</span> where <span class="math inline">\(\mathbf{x}_j\)</span> is a row-vector of one or more predictors for study <span class="math inline">\(j\)</span> (including a constant intercept). Introducing these predictors will alter the variance component estimates <span class="math inline">\(\hat\tau^2\)</span> and <span class="math inline">\(\hat\omega^2\)</span>, but the form of the weights will remain the same as above, and the intuitions still hold. This is because, for purposes of estimating <span class="math inline">\(\boldsymbol\beta\)</span>, the model is essentially the same as a meta-regression at the study level, using the study-specific average effect size estimates as input: <span class="math display">\[
\hat\theta_j = \mathbf{x}_j \boldsymbol\beta + \eta_j + \tilde{e}_j
\]</span> where <span class="math inline">\(\text{Var}(\tilde{e}_j) = \text{Var}(\hat\theta_j | \theta_j)\)</span>.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<p>Here is an illustration with the <code>corrdat</code> meta-analysis. In these data, the variable <code>college</code> indicates whether the effect size comes from a college-age sample; it varies only at the study level. The variable <code>males</code>, <code>binge</code>, and <code>followup</code> have some within-study variation, which I’ll by taking the average of each of these predictors at the study level:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>corrdat <span class="ot">&lt;-</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  corrdat <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(studyid) <span class="sc">%&gt;%</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">males_M =</span> <span class="fu">mean</span>(males),</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">binge_M =</span> <span class="fu">mean</span>(binge),</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">followup_M =</span> <span class="fu">mean</span>(followup)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Now let’s fit a meta-regression model using all of the study-level predictors:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>MVMR_fit <span class="ot">&lt;-</span> <span class="fu">rma.mv</span>(<span class="at">yi =</span> effectsize, <span class="at">V =</span> V_mat,</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">mods =</span> <span class="sc">~</span> college <span class="sc">+</span> males_M <span class="sc">+</span> binge_M <span class="sc">+</span> followup_M,  </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">random =</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> studyid <span class="sc">/</span> esid,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> corrdat)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(MVMR_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Multivariate Meta-Analysis Model (k = 171; method: REML)

  logLik  Deviance       AIC       BIC      AICc   
-86.6244  173.2488  187.2488  209.0327  187.9577   

Variance Components:

            estim    sqrt  nlvls  fixed        factor 
sigma^2.1  0.0297  0.1723     39     no       studyid 
sigma^2.2  0.1068  0.3268    171     no  studyid/esid 

Test for Residual Heterogeneity:
QE(df = 166) = 1083.6655, p-val &lt; .0001

Test of Moderators (coefficients 2:5):
QM(df = 4) = 13.0787, p-val = 0.0109

Model Results:

            estimate      se     zval    pval    ci.lb    ci.ub    
intrcpt      -0.0361  0.3678  -0.0982  0.9218  -0.7571   0.6849    
college       0.2660  0.1384   1.9215  0.0547  -0.0053   0.5373  . 
males_M       0.0023  0.0048   0.4753  0.6346  -0.0072   0.0118    
binge_M       0.3441  0.1570   2.1927  0.0283   0.0365   0.6518  * 
followup_M   -0.0023  0.0011  -2.0379  0.0416  -0.0044  -0.0001  * 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>As you might expect, between-study heterogeneity is reduced a bit by the inclusion of these predictors.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<p>We can check my claim of computational equivalence by fitting the meta-regression model at the study level. Here I’ll aggregate everything up to the study level and compute the study-level weights:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>tau_sq_reg <span class="ot">&lt;-</span> MVMR_fit<span class="sc">$</span>sigma2[<span class="dv">1</span>]</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>omega_sq_reg <span class="ot">&lt;-</span> MVMR_fit<span class="sc">$</span>sigma2[<span class="dv">2</span>]</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>corrdat_studylevel <span class="ot">&lt;-</span> </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  corrdat <span class="sc">%&gt;%</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(studyid) <span class="sc">%&gt;%</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">n_j =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_at</span>(<span class="fu">vars</span>(effectsize, n_j, V_bar, college, binge_M, followup_M, males_M), mean</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">V_cond =</span> (omega_sq_reg <span class="sc">+</span> (n_j <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> r <span class="sc">*</span> V_bar <span class="sc">+</span> V_bar) <span class="sc">/</span> n_j,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">w_j =</span> <span class="dv">1</span> <span class="sc">/</span> (tau_sq_reg <span class="sc">+</span> V_cond)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Now I can fit a study-level meta-regression model. I use the <code>weights</code> argument to ensure that the meta-regression is estimated using the <span class="math inline">\(w_j\)</span> weights:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>MR_study_fit <span class="ot">&lt;-</span> <span class="fu">rma</span>(<span class="at">yi =</span> effectsize, <span class="at">vi =</span> V_cond, </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">mods =</span> <span class="sc">~</span> college <span class="sc">+</span> males_M <span class="sc">+</span> binge_M <span class="sc">+</span> followup_M, </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">weights =</span> w_j, <span class="at">data =</span> corrdat_studylevel)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(MR_study_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Mixed-Effects Model (k = 39; tau^2 estimator: REML)

  logLik  deviance       AIC       BIC      AICc   
-13.0651   26.1303   38.1303   47.2884   41.2414   

tau^2 (estimated amount of residual heterogeneity):     0.0297 (SE = 0.0264)
tau (square root of estimated tau^2 value):             0.1723
I^2 (residual heterogeneity / unaccounted variability): 26.89%
H^2 (unaccounted variability / sampling variability):   1.37
R^2 (amount of heterogeneity accounted for):            37.90%

Test for Residual Heterogeneity:
QE(df = 34) = 46.5050, p-val = 0.0748

Test of Moderators (coefficients 2:5):
QM(df = 4) = 13.0787, p-val = 0.0109

Model Results:

            estimate      se     zval    pval    ci.lb    ci.ub    
intrcpt      -0.0361  0.3678  -0.0982  0.9218  -0.7571   0.6849    
college       0.2660  0.1384   1.9215  0.0547  -0.0053   0.5373  . 
males_M       0.0023  0.0048   0.4753  0.6346  -0.0072   0.0118    
binge_M       0.3441  0.1570   2.1927  0.0283   0.0365   0.6518  * 
followup_M   -0.0023  0.0011  -2.0379  0.0416  -0.0044  -0.0001  * 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The meta-regression coefficient estimates are essentially identical to those from the multi-variate meta-regression, although the between-study heterogeneity estimate differs slightly because it is based on maximizing the single-level model, conditional on an estimate of <span class="math inline">\(\omega^2\)</span>.</p>
</section>
<section id="and-beyond" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> And beyond!</h1>
<p>In true multi-variate models, the meta-regression specification would typically include indicators for each dimension of the model. More generally, we might have a model that includes predictors varying within study, encoding characteristics of the outcome measures, sub-groups, or treatment conditions corresponding to each effect size estimate. The weights in these model get substantially more complicated, not in the least because the weights <em>are specific to the predictors</em>. For instance, in a model with four within-study predictors, a different set of weights is used in estimating the coefficients corresponding to each predictor. As Dr.&nbsp;<a href="https://twitter.com/Richard_D_Riley">Richard Riley</a> noted on Twitter, relevant work on more complicated models includes <a href="https://doi.org/10.1177/0962280215611702">this great paper by Dan Jackson and colleagues</a> and <a href="https://doi.org/10.1177/0962280216688033">this paper by Riley and colleagues</a>. The latter paper demonstrates how multivariate models entail partial “borrowing of strength” across dimensions of the effect sizes, which is very helpful for building intuition about how these models work. I would encourage you to check out both papers if you are grappling with understanding how weights work in complex meta-regression models.</p>


</section>


<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a><div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Note that this model also encompasses the multi-level meta-analysis described by <a href="https://doi.org/10.1002/jrsm.35">Konstantopoulos (2011)</a> and <a href="https://doi.org/10.3758/s13428-012-0261-6">Van den Noortgate, et al.&nbsp;(2013)</a> as a special case, with <span class="math inline">\(r_{hij} = 0\)</span> for all <span class="math inline">\(h,i=1,...,n_j\)</span> and <span class="math inline">\(j = 1,...,k\)</span>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Perhaps that makes sense, if you’ve carefully selected the set of effect sizes for inclusion in your meta-analysis. However, it seems to me that it could sometimes lead to perverse results. Say that all studies but one include just a single effect size estimate, each using the absolute gold standard approach to assessing the outcome, but that one study took a “kitchen sink” approach and assessed the outcome a bunch of different ways, including the gold standard plus a bunch of junky scales. Inclusion of the junky scales will lead to within-study heterogeneity, which in turn will <em>pull the overall average effect size towards this study—the one with all the junk!</em> That seems less than ideal, and the sort of situation where it would be better to select from the study with multiple outcomes the single effect size estimate based on the outcome assessment that most closely aligns with the other studies.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Things get even simpler if the model does not include within-study random effects, as I discussed in <a href="../..\posts/sometimes-aggregating-effect-sizes-is-fine/">a previous post</a>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>However, this need not be the case—it’s possible that introducing between-study predictors could <em>increase</em> the estimate of between-study heterogeneity. Yes, that’s totally counter-intuitive. Multi-level models can be weird.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section><section class="quarto-appendix-contents" id="quarto-reuse"><h2 class="anchored quarto-appendix-heading">Reuse</h2><div class="quarto-appendix-contents"><div><a rel="license" href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a></div></div></section><section class="quarto-appendix-contents" id="quarto-citation"><h2 class="anchored quarto-appendix-heading">Citation</h2><div><div class="quarto-appendix-secondary-label">BibTeX citation:</div><pre class="sourceCode code-with-copy quarto-appendix-bibtex"><code class="sourceCode bibtex">@online{pustejovsky2020,
  author = {Pustejovsky, James E.},
  title = {Weighting in Multivariate Meta-Analysis},
  date = {2020-06-09},
  url = {https://mellifluous-buttercream-e2edd2.netlify.app/posts/weighting-in-multivariate-meta-analysis},
  langid = {en}
}
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre><div class="quarto-appendix-secondary-label">For attribution, please cite this work as:</div><div id="ref-pustejovsky2020" class="csl-entry quarto-appendix-citeas" role="listitem">
Pustejovsky, James E. 2020. <span>“Weighting in Multivariate
Meta-Analysis.”</span> June 9, 2020. <a href="https://mellifluous-buttercream-e2edd2.netlify.app/posts/weighting-in-multivariate-meta-analysis">https://mellifluous-buttercream-e2edd2.netlify.app/posts/weighting-in-multivariate-meta-analysis</a>.
</div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/mellifluous-buttercream-e2edd2\.netlify\.app");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://utteranc.es/client.js" repo="jepusto/jepusto-quarto" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>