---
title: 'Examining the effects of social stories on challenging behavior and prosocial
  skills in young children: A systematic review and meta-analysis'
author:
- name:
    given: Charis L.
    family: Wahman
- name:
    given: James E.
    family: Pustejovsky
- name:
    given: Michaelene M.
    family: Ostrosky
- name:
    given: Rosa Milagros
    family: Santos
date: 2022-02-01T00:00:00
categories:
- single-case design
- meta-analysis
- systematic review
links:
- text: Journal
  url: https://doi.org/10.1177/0271121419855692
  icon: newspaper
- icon: unlock-fill
  text: Pre-Print
  url: https://psyarxiv.com/fch6t/
- icon: code-slash
  text: Code
  url: https://osf.io/m3afs/
- icon: table
  text: Data
  url: https://osf.io/hk7fn/
citation:
  type: article-journal
  container-title: Topics in Early Childhood Special Education
  url: https://doi.org/10.1177/0271121419855692
  doi: 10.1016/j.jsp.2018.02.003
  volume: 41
  issue: 4
  page: 267-279

---

Social stories are a commonly used intervention practice in early childhood special education. Recent systematic reviews have documented the evidence-base for social stories, but findings are mixed. We examined the efficacy of social stories for young children (i.e., 3-5 years) with challenging behavior across 12 single-case studies, that included 30 participants. The What Works Clearinghouse standards for single case research design were used to evaluate the rigor of studies that included social stories as a primary intervention. For studies meeting standards, we synthesized findings on the efficacy of social stories using meta-analysis techniques and a recently developed parametric effect size measure, the log response ratio. Trends in participants’ response to treatment also were explored. Results indicate variability in rigor and efficacy for the use of social stories as an isolated intervention and in combination with other intervention approaches. Additional studies that investigate the efficacy of social stories as a primary intervention are warranted.


