---
title: 'Evaluating the Transition to College Mathematics Course in Texas high schools: Findings from the second year of implementation'
author:
- James E. Pustejovsky
- Megha Joshi
date: 2020-12-16T00:00:00
publish_date: 2020-12-16T00:00:00
publication_type: Report
publication: Greater Texas Foundation White Paper
organization: Greater Texas Foundation
location: Bryan, TX
categories:
- causal inference
- evaluation
- Transition to College Mathematics
links:
- text: White paper
  url: https://www.greatertexasfoundation.org/wp-content/uploads/2021/08/Pustejovsky-White-Paper-2020-REVISED.pdf
  icon: newspaper
- icon: file-pdf-fill
  text: PDF
  url: files/TCMC-Eval-Yr-2.pdf

---


Texas House Bill 5 introduced requirements that school districts partner with institutions of higher education to provide college preparatory courses in mathematics and English for high school seniors who are not yet college ready. As districts and college partners begin to respond to these provisions, there is a need for empirical research on the effects of different approaches to implementing the college preparatory courses. In response to House Bill 5 requirements, the Charles A. Dana Center has developed a model college preparatory mathematics course, Transition to College Mathematics Course (TCMC), which has been adopted by dozens of school districts across Texas over the past several school years. We examine the effects of TCMC on students’ progress into post-secondary education by comparing students who participated in TCMC during the 2017-18 school year (the second year of implementation) to observationally similar students from the same cohort but who did not enroll in the course. We find that students who took TCMC graduated at higher rates than comparison students. They had similar rates of overall enrollment in post-secondary education, but enrolled in community colleges at higher rates and in 4-year colleges or universities at lower rates than did comparison students. Enrollment tended to increase over the course of four semesters after high school graduation. Relative to comparison students, students who took TCMC were also less likely to take and less likely to pass college-level math coursework. These results must be interpreted cautiously because we were unable to fully assess and account for students’ college-readiness status at the start of their senior year.

