---
title: 'Analysis and meta-analysis of single-case designs with a standardized mean difference statistic: A primer and applications'
author:
- William R. Shadish
- Larry V. Hedges
- James E. Pustejovsky
date: 2014-04-01T00:00:00
publish_date: 2014-04-01T00:00:00
publication_type: Journal article
publication: Journal of School Psychology
volume: 52
issue: 
pages: 123-147
categories:
- single-case design
- design-comparable SMD
- effect size
links:
- text: Journal
  url: https://doi.org/10.1016/j.jsp.2013.11.005
  fa-icon: newspaper

---


This article presents a d-statistic for single-case designs that is in the same metric as the d-statistic used in between-subjects designs such as randomized experiments and offers some reasons why such a statistic would be useful in SCD research. The d has a formal statistical development, is accompanied by appropriate power analyses, and can be estimated using user-friendly SPSS macros. We discuss both advantages and disadvantages of d compared to other approaches such as previous d-statistics, overlap statistics, and multilevel modeling. It requires at least three cases for computation and assumes normally distributed outcomes and stationarity, assumptions that are discussed in some detail. We also show how to test these assumptions. The core of the article then demonstrates in depth how to compute d for one study, including estimation of the autocorrelation and the ratio of between case variance to total variance (between case plus within case variance), how to compute power using a macro, and how to use the d to conduct a meta-analysis of studies using single-case designs in the free program R, including syntax in an appendix. This syntax includes how to read data, compute fixed and random effect average effect sizes, prepare a forest plot and a cumulative meta-analysis, estimate various influence statistics to identify studies contributing to heterogeneity and effect size, and do various kinds of publication bias analyses. This d may prove useful for both the analysis and meta-analysis of data from SCDs.

