---
title: 'Functional assessment-based interventions for students with or at-risk for
  high incidence disabilities: Field-testing single-case synthesis methods'
author:
- name:
    given: Eric A.
    family: Common
- name:
    given: Kathleen L.
    family: Lane
- name:
    given: James E.
    family: Pustejovsky
- name:
    given: Austin H.
    family: Johnson
- name:
    given: Liane E.
    family: Johl
date: 2017-03-01T00:00:00
categories:
- design-comparable SMD
- effect size
- meta-analysis
- response ratio
- single-case design
- systematic review
links:
- text: Journal
  url: https://doi.org/10.1177/0741932517693320
  icon: newspaper
citation:
  type: article-journal
  container-title: Remedial and Special Education
  doi: 10.1177/0741932517693320
  volume: 38
  issue: 6
  page: 331-352

---

This systematic review investigated one systematic approach to designing, implementing, and evaluating functional assessment–based interventions (FABI) for use in supporting school-age students with or at-risk for high-incidence disabilities. We field tested several recently developed methods for single-case design syntheses. First, we appraised the quality of individual studies and the overall body of work using Council for Exceptional Children’s standards. Next, we calculated and meta-analyzed within-case and between-case effect sizes. Results indicated that studies were of high methodological quality, with nine studies identified as being methodologically sound and demonstrating positive outcomes across 14 participants. However, insufficient evidence was available to classify the evidence base for FABIs due to small number of participants within (fewer than recommended three) and across (fewer than recommended 20) studies. Nonetheless, average within-case effect sizes were equivalent to increases of 118% between baseline and intervention phases. Finally, potential moderating variables were examined. Limitations and future directions are discussed.

