---
title: 'Investigating narrative performance in children with developmental language
  disorder: A systematic review and meta-analysis'
author:
- name:
    given: Katherine L.
    family: Winters
- name:
    given: Javier
    family: Jasso
- name:
    given: James E.
    family: Pustejovsky
- name:
    given: Courtney
    family: Byrd
date: 2022-09-30T00:00:00
categories:
- narrative assessment
- developmental language disorder
- meta-analysis
- dependent effect sizes
- robust variance estimation
image-alt: Forest Plot of TD-DLD Group Differences in Narrative Performance
links:
- text: Journal
  url: https://doi.org/10.1044/2022_JSLHR-22-00017
  icon: newspaper
- text: Supplementary materials
  url: https://osf.io/dgz7m/
- icon: unlock-fill
  text: Pre-Print
  url: https://psyarxiv.com/bcky8/
- icon: code-slash
  text: Code
  url: https://osf.io/ybdx7/
- icon: table
  text: Data
  url: https://osf.io/ybdx7/
citation:
  type: article-journal
  container-title: Journal of Speech, Language, and Hearing Research
  url: https://doi.org/10.1044/2022_JSLHR-22-00017
  doi: 10.1016/j.jsp.2018.02.003
  volume: 65
  issue: 10
  page: 3908-3929

---

__Purpose__: Speech-language pathologists (SLPs) typically examine narrative performance when completing a comprehensive language assessment. However, there is significant variability in the methodologies used to evaluate narration. The primary aims of this systematic review and meta-analysis were to a) investigate how narrative assessment type (e.g., macrostructure, microstructure, internal state language) differentiates typically developing (TD) children from children with developmental language disorder (DLD), or, TD–DLD group differences, b) identify specific narrative assessment measures (e.g., number of different words) that result in greater TD–DLD differences, and, c) evaluate participant and sample characteristics (e.g., DLD inclusionary criteria) that may uniquely influence performance differences.

__Method__: Three electronic databases (PsychInfo, ERIC, and PubMed) and ASHAWire were searched on July 30, 2019 to locate studies that reported oral narrative language measures for both DLD and TD groups between ages 4 and 12 years; studies focusing on written narration or other developmental disorders only were excluded. Thirty-seven primary studies were identified via a three-step study selection procedure. We extracted data related to the sample participants, the narrative task(s) and assessment measures, and research design. Standardized mean differences using a bias-corrected Hedges’ $g$ were the calculated effect sizes ($N = 382$). Research questions were analyzed using mixed-effects meta-regression with robust variance estimation to account for effect size dependencies.

__Results__: Searches identified eligible studies published between 1987 and 2019. An overall meta-analysis using 382 effect sizes obtained across 37 studies showed that children with DLD had decreased narrative performance relative to TD peers, with summary estimates ranging from -0.850, 95% CI [-1.016, -0.685] to -0.794, 95% CI [-0.963, -0.624], depending on the correlation assumed. Across all models, effect size estimates showed significant heterogeneity both between and within studies, even after accounting for effect size-, sample-, and study-level predictors. Grammatical accuracy (microstructure) and story grammar (macrostructure) yielded the most consistent evidence of significant TD–DLD group differences across statistical models.

__Conclusions__: Present findings suggest some narrative assessment measures may yield significantly different performance between children with and without DLD. However, researchers need to be consistent in their inclusionary criteria, their description of sample characteristics, and in their reporting of the correlations of measures, in order to determine which assessment measures are more likely to yield group differences.

