---
title: Four methods for analyzing partial interval recording data, with application to single-case research
author:
- James E. Pustejovsky
- Daniel M. Swan
date: 2015-06-19T00:00:00
publish_date: 2015-06-19T00:00:00
publication_type: Journal article
publication: Multivariate Behavioral Research
volume: 50 
issue: 3
pages: 365-380
categories:
- alternating renewal process
- effect size
- response ratio
- single-case design
- behavioral observation
links:
- text: Supplementary materials
  url: /files/4-PIR-Methods-Appendix.pdf
- text: Journal
  url: http://doi.org/10.1080/00273171.2015.1014879
  icon: newspaper
- icon: unlock-fill
  text: Pre-Print
  url: /files/4-PIR-methods-MBR.pdf
---

Partial interval recording (PIR) is a procedure for collecting measurements during direct observation of behavior. It is used in several areas of educational and psychological research, particularly in connection with single-case research. Measurements collected using partial interval recording suffer from construct invalidity because they are not readily interpretable in terms of the underlying characteristics of the behavior. Using an alternating renewal process model for the behavior under observation, we demonstrate that ignoring the construct invalidity of PIR data can produce misleading inferences, such as inferring that an intervention reduces the prevalence of an undesirable behavior when in fact it has the opposite effect. We then propose four different methods for analyzing PIR summary measurements, each of which can be used to draw inferences about interpretable behavioral parameters. We demonstrate the methods by applying them to data from two single-case studies of problem behavior.

