---
title: 'Interventions to enhance self-efficacy in cancer patients and survivors: A meta-analysis of randomized controlled trials'
authors:
- Tom V. Merluzzi
- James E. Pustejovsky
- Errol J. Philip
- Stephanie J. Sohl
- Mark Berendsen
- John A. Salsman
date: 2019-06-06T00:00:00
publish_date: 2019-06-06T00:00:00
publication_type: Journal article
publication: Psycho-Oncology
volume: 28
issue: 9
pages: 1781-1790
categories:
- psycho-social intervention
- cancer
- meta-analysis
- self-efficacy
- systematic review
links:
- text: Journal
  url: https://doi.org/10.1002/pon.5148
  icon: fa newspaper
- fa-icon: table
  text: Data
  url: https://curate.nd.edu/show/jw827943c2d

---


Objective: Self-efficacy expectations are associated with improvements in problematic outcomes widely considered clinically significant (i.e., emotional distress, fatigue, pain), related to positive health behaviors, and, as a type of personal agency, inherently valuable. Self-efficacy expectancies, estimates of confidence to execute behaviors, are important in that changes in selfefficacy expectations are positively related to future behaviors that promote health and wellbeing. The current meta-analysis investigated the impact of psychological interventions on self-efficacy expectations for a variety of health behaviors among cancer patients. Methods: Ovid Medline, PsycINFO, CINAHL, EMBASE, Cochrane Library, and Web of Science were searched with specific search terms for identifying randomized controlled trials (RCTs) that focused on psychologically-based interventions. Included studies had: 1) an adult cancer sample, 2) a self-efficacy expectation measure of specific behaviors and 3) an RCT design. Standard screening and reliability procedures were used for selecting and coding studies. Coding included theoretically informed moderator variables. Results: Across 79 RCTs, 223 effect sizes, and 8678 participants, the weighted average effect of self-efficacy expectations was estimated as g=0.274 (p<.001). Consistent with Self-Efficacy Theory, the average effect for in-person intervention delivery (g=0.329) was significantly greater than for all other formats (g=0.154, p=.023; e.g., audiovisual, print, telephone, web/internet). Conclusions: The results establish the impact of psychological interventions on self-efficacy expectations as comparable in effect size to commonly reported outcomes (distress, fatigue, pain). Additionally, the result that in-person interventions achieved the largest effect is supported by Social Learning Theory and could inform research related to the development and evaluation of interventions.

