---
title: Question-order effects in social network name generators
author:
- name:
    given: James E.
    family: Pustejovsky
- name:
    given: James P.
    family: Spillane
date: 2009-10-01T00:00:00
categories:
- question-order
- social networks
links:
- text: Journal
  url: http://doi.org/10.1016/j.socnet.2009.06.001
  icon: newspaper
- icon: unlock-fill
  text: Pre-Print
  url: /files/Question-order-effects-in-social-network-name-generators.pdf
- icon: table
  text: Data
  url: https://www.icpsr.umich.edu/icpsrweb/instructors/series/00255
citation:
  type: article-journal
  container-title: Social Networks
  doi: 10.1016/j.socnet.2009.06.001
  volume: 31
  issue: 4
  page: 221-229

---

Social network surveys are an important tool for empirical research in a variety of fields, including the study of social capital and the evaluation of educational and social policy. A growing body of methodological research sheds light on the validity and reliability of social network survey data regarding a single relation, but much less attention has been paid to the measurement of multiplex networks and the validity of comparisons among criterion relations. In this paper, we identify ways that surveys designed to collect multiplex social network data might be vulnerable to question-order effects. We then test several hypotheses using a split-ballot experiment embedded in an online multiple name generator survey of teachers’ advice networks, collected for a study of complete networks. We conclude by discussing implications for the design of multiple name generator social network surveys.


