---
title: 'Synthesis of dependent effect sizes: Versatile models through metafor and
  clubSandwich'
author:
- James E. Pustejovsky
date: 2021-01-21T09:00:00
publish_date: 2021-01-21T12:00:00
event: Evidence Synthesis and Meta-Analysis in R Conference
event_short: ESMARConf2021
event_url: https://www.eshackathon.org/events/2021-01-ESMAR.html
location: online
links:
- faicon: file
  text: PDF
  url: https://osf.io/preprints/metaarxiv/vyfcj/
- faicon: person-chalkboard
  text: Slides
  url: /files/ESMARConf2021-RVE-with-clubSandwich.pdf
- faicon: youtube
  text: Video
  url: https://youtu.be/Q9Nce5pxebY?t=66

---


Across scientific fields, large meta-analyses often involve dependent effect size estimates. Robust variance estimation (RVE) methods provide a way to include all dependent effect sizes in a single meta-analysis model, even when the nature of the dependence is unknown. RVE uses a working model of the dependence structure, but the two currently available working models (available in the robumeta package) are limited to each describing a single type of dependence. We describe a workflow combining two existing packages, metafor and clubSandwich, that can be used to implement an expanded set of working models, offering benefits in terms of better capturing the types of data structures that occur in practice and improving the efficiency of meta-analytic model estimates.

