---
title: Easy, cluster-robust standard errors with the clubSandwich package
author:
- James E. Pustejovsky
date: 2022-02-03T10:00:00
publish_date: 2022-02-03T11:00:00
event: Oslo R User Group Meetup
event_short: OsloRUG
event_url: https://www.meetup.com/Oslo-useR-Group/events/283050203/
location: online
links:
- fa-icon: person-chalkboard
  text: Slides
  url: /files/clubSandwich-Oslo-RUG-2022-02-03.pdf
- fa-icon: youtube
  text: Video
  url: https://youtu.be/cjBByCn_PK8

---


Cluster-robust variance estimation methods (also known as sandwich estimators, linearization estimators, or simply "clustered" standard errors) are a standard inferential tool in many different areas of applied statistics. They are appealing because they provide a means to do inference for regression models without relying on strong assumptions about the distribution or dependence structure of errors. However, standard cluster-robust variance estimators are based on large-sample approximations and can perform poorly when based on a small number of clusters. In this talk, I will provide an overview of some refinements to cluster-robust variance estimators, as implemented on the clubSandwich package (https://CRAN.R-project.org/package=clubSandwich), that perform well even with a limited number of clusters. I will provide a brief, high-level sketch of the theory behind the refined methods, discuss the practical rationale for using the methods, and demonstrate their application with the clubSandwich package, focusing in particular on linear mixed models. In addition to linear mixed models, the methods are available for a range of regression models and estimation methods, including ordinary least squares, weighted least squares, two-stage least squares, generalized linear models, and meta-regression models.

