---
title: A standardized mean difference effect size for multiple baseline designs
authors:
- Larry V. Hedges
- James E. Pustejovsky
- William R. Shadish
date: 2013-08-23T00:00:00
publish_date: 2013-08-23T00:00:00
publication_type: Journal article
publication: Research Synthesis Methods
volume: 4
issue: 4
pages: 324-341
categories:
- design-comparable SMD
- effect size
- single-case design
links:
- text: Journal
  url: https://dx.doi.org/10.1002/jrsm.1086
  icon: fa newspaper
- text: R package
  url: https://CRAN.R-project.org/package=scdhlm
  icon: fa gift
- text: Web app
  url: https://jepusto.shinyapps.io/scdhlm/
  icon: fa tablet-screen-button

---
{{< include '../_publication_header.qmd' >}}


Single-case designs are a class of research methods for evaluating treatment effects by measuring outcomes repeatedly over time while systematically introducing different condition (e.g., treatment and control) to the same individual. The designs are used across fields such as behavior analysis, clinical psychology, special education, and medicine. Emerging standards for single-case designs have focused attention on methods for summarizing and meta-analyzing findings and on the need for effect sizes indices that are comparable to those used in between-subjects designs. In the previous work, we discussed how to define and estimate an effect size that is directly comparable to the standardized mean difference often used in between-subjects research based on the data from a particular type of single-case design, the treatment reversal or (AB)k design. This paper extends the effect size measure to another type of single-case study, the multiple baseline design. We propose estimation methods for the effect size and its variance, study the estimators using simulation, and demonstrate the approach in two applications.

