---
title: 'Comparison of competing approaches to analyzing cross-classified data: Random effects models, ordinary least squares, or fixed effects with cluster robust standard errors'
authors:
- Young Ri Lee
- James E. Pustejovsky
date: 2023-03-09T00:00:00
publish_date: 2023-03-09T00:00:00
publication_type: Journal article
publication: Psychological Methods 
volume: 
issue: 
pages: advance online publication
categories:
- simulation
- random effects
- robust variance estimation
- fixed effects
links:
- text: Journal
  url: https://doi.org/10.1037/met0000538
  icon: fa newspaper
- text: Supplementary materials
  url: https://osf.io/s7hr3/
- fa-icon: lock-open
  text: Pre-Print
  url: https://psyarxiv.com/f9mr2

---


Cross-classified random effects modeling (CCREM) is a common approach for analyzing cross-classified data in education. However, when the focus of a study is on the regression coefficients at level one rather than on the random effects, ordinary least squares regression with cluster robust variance estimators (OLS-CRVE) or fixed effects regression with CRVE (FE-CRVE) could be appropriate approaches. These alternative methods may be advantageous because they rely on weaker assumptions than what is required by CCREM. We conducted a Monte Carlo Simulation study to compare the performance of CCREM, OLS-CRVE, and FE-CRVE in models with crossed random effects, including conditions where homoscedasticity assumptions and exogeneity assumptions held and conditions where they were violated. We found that CCREM performed the best when its assumptions are all met. However, when homoscedasticity assumptions are violated, OLS-CRVE and FE-CRVE provided similar or better performance than CCREM. FE-CRVE showed the best performance when the exogeneity assumption is violated. Thus, we recommend two-way FE-CRVE as a good alternative to CCREM, particularly if the homoscedasticity or exogeneity assumptions of the CCREM might be in doubt.

