---
title: A standardized mean difference effect size for single case designs
author:
- name:
    given: Larry V.
    family: Hedges
- name:
    given: James E.
    family: Pustejovsky
- name:
    given: William R.
    family: Shadish
date: 2012-08-14T00:00:00
categories:
- design-comparable SMD
- effect size
- single-case design
links:
- text: Journal
  url: https://dx.doi.org/10.1002/jrsm.1052
  icon: newspaper
- text: R package
  url: https://CRAN.R-project.org/package=scdhlm
  icon: box2
- text: Web app
  url: https://jepusto.shinyapps.io/scdhlm/
  icon: tablet
citation:
  type: article-journal
  container-title: Research Synthesis Methods
  url: https://dx.doi.org/10.1002/jrsm.1052
  doi: 10.1016/j.jsp.2018.02.003
  volume: 3
  page: 224-239

---

Single case designs are a set of research methods for evaluating treatment effects by assigning different treatments to the same individual and measuring outcomes over time and are used across fields such as behavior analysis, clinical psychology, special education, and medicine. Emerging standards for single case designs have focused attention on the need for effect sizes for summarizing and meta-analyzing findings from the designs; although many effect size measures have been proposed, there is little consensus regarding their use. This article proposes a new effect size measure for single case research that is directly comparable with the standardized mean difference (Cohen's d) often used in between-subjects designs. Techniques are provided for estimating the new effect size, as well as its variance, from balanced or unbalanced treatment reversal designs. The proposed estimation methods are further evaluated using a simulation study and then demonstrated in two applications.


