---
title: Measurement-comparable effect sizes for single-case studies of free-operant behavior
author: 
 - James E. Pustejovsky
date: 2015-09-01T00:00:00
publish_date: 2015-09-01T00:00:00
publication_type: Journal article
publication: Psychological Methods
volume: 20
issue: 3
pages: 342-359
categories:
- alternating renewal process
- effect size
- response ratio
- single-case design
- behavioral observation
links:
- text: Supplementary materials
  url: /files/Measuerment-comparable-ES-Appendix.pdf
- text: Journal
  url: http://dx.doi.org/10.1037/met0000019
  icon: newspaper
- icon: unlock-fill
  text: Pre-Print
  url: /files/Measurement-comparable-ES.pdf

---


Single-case research comprises a set of designs and methods for evaluating the effects of interventions, practices, or programs on individual cases, through comparison of outcomes measured at different points in time. Although there has long been interest in meta-analytic techniques for synthesizing single-case research, there has been little scrutiny of whether proposed effect sizes remain on a directly comparable metric when outcomes are measured using different operational procedures. Much of single-case research focuses on behavioral outcomes in free-operant contexts, which may be measured using a variety of different direct observation procedures. This article describes a suite of effect sizes for quantifying changes in free-operant behavior, motivated by an alternating renewal process model that allows measurement comparability to be established in precise terms. These effect size metrics have the advantage of comporting with how direct observation data are actually collected and summarized. Effect size estimators are proposed that are applicable when the behavior being measured remains stable within a given treatment condition. The methods are illustrated by 2 examples, including a re-analysis of a systematic review of the effects of choice-making opportunities on problem behavior.

