---
title: Research Design and Methods for Psychology and Education
place: UT Austin
---

This course surveys essential concepts and methods used in quantitative empirical research in the fields of education and psychology, in order to prepare students both to be informed consumers of research and to conduct empirical research of their own. The course is organized around four main themes: measurement, populations and sampling, experimental causal research, and quasi-experimental causal research. On each theme, we read relevant theoretical and methodological literature, discuss empirical research in light of those concepts, and develop research proposals using the methods that we discuss. Throughout, emphasis is on building intuition and heuristics regarding research designs and methods.

* [2019 (Fall) Syllabus](/teaching/Research-design/EDP381C-2-10575-Research-Design-2019F.pdf)
* [2019 (Spring) Syllabus](/teaching/Research-design/EDP381C-2-10775-Research-Design-2019S.pdf)
* [2018 (Fall) Syllabus](/teaching/Research-design/EDP381C-2-10540-Research-Design-2018F.pdf)
* [2018 (Spring) Syllabus](/teaching/Research-design/EDP381C-2-10200-Research-Design-2018S.pdf)
* [2017 (Spring) Syllabus](/teaching/Research-design/EDP381C-2-10895-Research-Design-2017S.pdf)
* [2016 (Fall) Syllabus](/teaching/Research-design/EDP381C-2-10770-Research-Design-2016F.pdf)
* [2016 (Spring) Syllabus](/teaching/Research-design/EDP381C-2-10790-Research-Design-2016S.pdf)
* [2015 (Fall) Syllabus](/teaching/Research-design/EDP381C-2-10790-Research-Design-2015F.pdf)
* [2015 (Spring) Syllabus](/teaching/Research-design/EDP384-10594-Research-Design-2015S.pdf)
* [2014 (Fall) Syllabus](/teaching/Research-design/EDP384-10977-Research-Design-2014F.pdf)
* [2014 (Spring) Syllabus](/teaching/Research-design/EDP384-11212-Research-Design-2014S.pdf)
* [2013 (Fall) Syllabus](/teaching/Research-design/EDP384-10615-Research-Design-2013F.pdf)

