---
title: Introduction to the special issue on single-case systematic reviews and meta-analysis
authors:
- Daniel M. Maggin
- Kathleen L. Lane
- admin
date: 2017-11-01T00:00:00
publish_date: 2017-11-01T00:00:00
publication_type: Journal article
publication: _Remedial and Special Education, 38_(6), 323-330
categories:
- effect size
- meta-analysis
- single-case design
links:
- text: Journal
  url: http://dx.doi.org/10.1177/0741932517717043
  icon: fa newspaper

---
{{< include '../_publication_header.qmd' >}}


This special issue provides an update on recent conceptual and methodological developments for conducting systematic reviews and meta-analyses of single-case research. In this introductory article, we (a) describe the important role of systematic reviews and meta-analyses within special education; (b) discuss several methodological issues authors must consider when planning and conducting a rigorous single-case review; and (c) summarize current approaches for addressing each of these issues. Following this overview, we describe each article in the special issue, paying particular attention to the methodological areas highlighted. We conclude with recommendations for continued research and development in several areas.

