---
title: Systematic review and meta-analysis of stay-play-talk interventions for improving social behaviors of young children
author:
- Jennifer R. Ledford
- James E. Pustejovsky
date: 2021-01-05T00:00:00
publish_date: 2021-01-05T00:00:00
publication_type: Journal article
publication: Journal of Positive Behavioral Interventions
volume: 25
issue: 1
pages: 65-77
categories:
- meta-analysis
- response ratio
- single-case design
- systematic review
image: Forest plots of LRRi estimates for peer and focal participants
links:
- text: Journal
  url: https://doi.org/10.1177/1098300720983521
  icon: newspaper
- text: Supplementary materials
  url: https://osf.io/m263p/
- icon: unlock-fill
  text: Pre-Print
  url: https://osf.io/u7cph/
---

Stay-play-talk (SPT) is a peer-mediated intervention which involves training peer implementers to stay in proximity to, play with, and talk to a focal child who has disabilities or lower social competence. This systematic review and meta-analysis investigated the contexts in which SPT interventions have been conducted, the methodological adequacy of the research assessing its effects, and the outcomes for both peer implementers and focal children. Studies have primarily occurred in inclusive preschool settings during free play activities, with researchers serving as facilitators. Average effects were positive for both peer implementers and focal children, although considerable heterogeneity across studies was observed. Additional research is needed to determine what peer implementer and focal child characteristics moderate intervention success, what modifications are needed for children who have complex communication needs, and optimal procedural variations (e.g., group size, training time).
