---
title: 'Between-case standardized effect size analysis of single case design: Examination
  of the two methods'
author:
- name:
    given: Samuel L.
    family: Odom
- name:
    given: Erin E.
    family: Barton
- name:
    given: Brian
    family: Reichow
- name:
    given: Hariharan
    family: Swaminathan
- name:
    given: James E.
    family: Pustejovsky
date: 2018-06-02T00:00:00
categories:
- single-case design
- design-comparable SMD
- effect size
links:
- text: Journal
  url: https://doi.org/10.1016/j.ridd.2018.05.009
  icon: newspaper
citation:
  type: article-journal
  container-title: Research in Developmental Disabilities
  url: https://doi.org/10.1016/j.ridd.2018.05.009
  doi: 10.1016/j.jsp.2018.02.003
  volume: 79
  page: 88-96

---

An increasing movement in single case research is to employ statistical analyses as one form of data analysis. Researchers have proposed different statistical approaches. The purpose of this paper is to examine the utility and discriminant validity of two novel types of between-case standardized effect size analyses with two existing systematic reviews. The between-case analyses found greater effect sizes for the studies in the object play review and smaller effect sizes for studies of sensory intervention, which were consistent with the overall conclusions reached in the original systematic reviews. These findings provide evidence of discriminant validity, although concerns remain around the methods’ utility across different single case research designs. Future directions for research and development also are provided.

