---
title: A gradual effects model for single-case designs
author:
- name:
    given: Daniel M.
    family: Swan
- name:
    given: James E.
    family: Pustejovsky
date: 2018-05-01T00:00:00
categories:
- effect size
- non-linear model
- response ratio
- single-case design
links:
- text: Journal
  url: https://doi.org/10.1080/00273171.2018.1466681
  icon: newspaper
- text: Supplementary materials
  url: https://osf.io/uzkq6/
- icon: unlock-fill
  text: Pre-Print
  url: https://psyarxiv.com/vh964/
- text: R package
  url: https://CRAN.R-project.org/package=SingleCaseES
  icon: box2
- text: Web app
  url: https://jepusto.shinyapps.io/gem-scd/
  icon: tablet
citation:
  type: article-journal
  container-title: Multivariate Behavioral Research
  doi: 10.1080/00273171.2018.1466681
  volume: 53
  issue: 4
  page: 574-593

---

Single-case designs are a class of repeated measures experiments used to evaluate the effects of interventions for specialized populations, such as individuals with low-incidence disabilities. There has been growing interest in systematic reviews and syntheses of evidence from single-case designs, but there remains a need to further develop appropriate statistical models and effect sizes for data from the designs. We propose a novel model for single-case data that exhibit non-linear time trends created by an intervention that produces gradual effects, which build up and dissipate over time. The model expresses a structural relationship between a pattern of treatment assignment and an outcome variable, making it appropriate for both treatment reversal and multiple baseline designs. It is formulated as a generalized linear model so that it can be applied to outcomes measured as frequency counts or proportions, both of which are commonly used in single-case research, while providing readily interpretable effect size estimates such as log response ratios or log odds ratios. We demonstrate the gradual effects model by applying it to data from a single-case study and examine the performance of proposed estimation methods in a Monte Carlo simulation of frequency count data.

