---
title: Design & Analysis of Quasi-Experiments for Causal Inference
place: UW Madison
---

The course begins with an introduction to the potential outcomes framework for expressing causal quantities, followed by an examination of (idealized) simple and block randomized experiments as prototypes for learning about causal effects. The remainder of the course covers theory and data-analysis strategies for drawing causal inferences from four quasi-experimental designs: instrumental variables approaches, regression discontinuity designs, non-equivalent control group designs (using techniques such as matching and propensity score weighting), and comparative interrupted time series designs. For each design, we will consider (i) the core strategy for identifying a causal effect, (ii) corresponding statistical approaches for estimating the effect, and (iii) strategies and design elements for strengthening the design. Further, advanced topics will be covered based on student interest.

- [2023 (Fall) syllabus](/teaching/Quasi-Experimental/EDPSYCH-963-001-Quasi-Experiments-2023-Fall-syllabus.pdf) and [reading list](/teaching/Quasi-Experimental/EDPSYCH-963-001-Quasi-Experiments-2023-Fall-reading-list.pdf)
- [2021 (Fall) syllabus](/teaching/Quasi-Experimental/EDPSYCH-963-001-Quasi-Experiments-2021-Fall-syllabus.pdf) and [reading list](/teaching/Quasi-Experimental/EDPSYCH-963-001-Quasi-Experiments-2021-Fall-reading-list.pdf)

