---
title: 'Analyzing single-case designs: d, G, hierarchical models, Bayesian estimators, generalized additive models, and the hopes and fears of researchers about analyses'
author:
- name:
    given: William R.
    family: Shadish
- name:
    given: Larry V.
    family: Hedges
- name:
    given: James E.
    family: Pustejovsky
- name:
    given: David
    family: Rindskopf
- name:
    given: Jonathan G.
    family: Boyajian
- name:
    given: Kristynn J.
    family: Sullivan
date: 2014-07-18T00:00:00
categories:
- single-case design
- design-comparable SMD
- effect size
- hierarchical models
links: 
- text: Publisher
  url: https://doi.org/10.1037/14376-009
  icon: newspaper
- icon: unlock-fill
  text: Pre-Print
  url: https://drive.google.com/file/d/1PfVFP4OY-_V0LrlJ-EAny1qVpITVJL_j/view
citation: 
  type: chapter
  container-title: "Single-Case Intervention Research: Methodological and Data-Analysis Advances"
  editor: 
  - name: 
      given: Thomas R.
      family: Kratochwill
  - name:
      given: Joel R.
      family: Levin
  publisher: American Psychological Association
  publisher-place: Washington, DC
  chapter-number: 8
  page: 247-281
  doi: 10.1037/14376-009
  url: https://doi.org/10.1037/14376-009
---

New approaches to the analyses of single-case designs are proliferating, which some single-case design researchers welcome and others view with skepticism. In this chapter we describe some of the analyses that we have been exploring, all of which can be conceptualized as versions of hierarchical models as a unifying framework. The approaches include a d-statistic for the (AB)k design that estimates the same parameter as the usual between-groups d-statistic, Bayesian approaches to the same and similar models, hierarchical generalized linear models that model outcomes as binomial or Poisson rather than the usual assumptions of normality, and semiparametric generalized additive models that allow diagnosis of trend and linearity. Throughout, we illustrate the analyses using a common example and show how the different analyses provide different insights into the data. We conclude with a discussion of potential criticisms and skepticism expressed by some researchers about such analyses, along with reasons why the field is increasingly likely to develop and use such analyses despite the criticisms.

