---
title: Causal Inference
place: UT Austin
---

This course introduces the contemporary statistical approach to addressing questions about the causal effects of programs, policies, or interventions, with a focus on applied data-analysis strategies and interpretation. The course begins with an introduction to the potential outcomes framework for expressing causal quantities, followed by an examination of (idealized) simple and block randomized experiments as prototypes for learning about causal effects. The remainder of the course covers theory and data-analysis strategies for drawing causal inferences from observational studies, in which treatment conditions are not randomly assigned. Analysis techniques such as matching methods, propensity-score methods, and instrumental variables are covered both in theory and in application. Further, advanced topics are covered based on student interest.

* [2020 (Spring) Syllabus](/teaching/Causal-Inference/EDP-381C-10930-Causal-inference-2020S.pdf)
* [2017 (Fall) Syllabus](/teaching/Causal-Inference/EDP-381C-10705-Causal-inference-2017F.pdf)
* [2014 (Fall) Syllabus](/teaching/Causal-Inference/EDP-384-25-Causal-inference-2014F-syllabus.pdf)

